name: terraform

on: [pull_request]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: hashicorp/terraform-github-actions/fmt@v0.3.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: "./terraform"
          TF_ACTION_WORKSPACE: "turno"
