name: CI

on: [pull_request]

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/terraform-github-actions/fmt@0.3.5
      env:
       - TF_ACTION_WORKING_DIR = "terraform"
       - TF_ACTION_WORKSPACE = "turno"
